### ISSUE TITLE
Every menu navigation opens a new page instead of replacing the old one

### ISSUE THREAD

**Issue by rainthundermoon** [JonathanCoe/bitseal#7]
Every time I open a page from the menu such as inbox, sent, compose my addresses address book etc the link comes up as a new page, so that every time the back button is pressed the app goes back by one page. Opening inbox 5 times opens 5 pages ontop of one anothert which then means I must press back 5 times to exit the program. This also leaves sent messages up, and it worries me that this may be keeping things in memory which need not be simply sitting open. Pressing the inbox button 20 times may end up using 20x the system memory that it should.

**Comment by JonathanCoe** [comment]
Hey, thanks a lot for reporting this problem. It should be fixed in commits ec94636 and 6e2834f.
